
apiVersion: v1
kind: Service
metadata:
  name: backbank
  labels:
    app: mastercard-backbank
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: mastercard-backbank
    tier: web
  type: LoadBalancer
  loadBalancerIP: 35.238.171.90 # "YOUR.IP.ADDRESS.HERE"
  externalTrafficPolicy: Local
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
#https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#step_2b_using_an_ingress
#https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/